---
apiVersion: v1
kind: Secret
metadata:
  name: neutron-switch-config
  namespace: openstack
stringData:
  03-ml2-genericswitch.conf: |
    [ngs]
    session_log_file = /var/log/neutron/ngs.log

    [genericswitch:dell-hostname-oct4]
    device_type = netmiko_dell_force10
    ngs_mac_address = 68:4f:64:1d:01:d5
    ngs_save_configuration = True
    ip = ip address
    username = admin
    password = password
    secret = password

type: Opaque
