apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: osp-enp7s0f1np1-host-192-168-60-143
spec:
  desiredState:
    interfaces:
      - description: internalapi vlan interface
        ipv4:
          address:
            - ip: 172.17.0.11
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: internalapi
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "393"
          reorder-headers: true

    
      - description: tenant vlan interface
        ipv4:
          address:
            - ip: 172.19.0.11
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: tenant
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "429"
          reorder-headers: true
      
      - description: ironic vlan interface
        ipv4:
          address:
            - ip: 172.20.1.18
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        mtu: 1500
        name: ironic
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "370"
          reorder-headers: true

      - description: Configuring enp7s0f1np1
        ipv4:
          address:
            - ip: 192.168.122.18
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        mtu: 1500
        name: enp7s0f1np1
        state: up
        type: ethernet

      - description: OBM vlan interface for moc-obm-mgmt
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
        mtu: 1500
        name: obm
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "911"
          reorder-headers: true

  nodeSelector:
    kubernetes.io/hostname: host-192-168-60-143
    node-role.kubernetes.io/worker: ""