apiVersion: v1
baseDomain: <BASE_DOMAIN>
networking:
  networkType: OVNKubernetes
  machineCIDR: <MACHINE_CIDR>
  clusterNetwork:
  - cidr: "10.128.0.0/14"
    hostPrefix: 23
  serviceNetwork:
  - "172.30.0.0/16"
metadata:
  name: <CLUSTER_NAME>
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    externalBridge: "baremetal"
    bootstrapProvisioningIP: <BOOTSTRAP_PROVISIONING_IP>
    provisioningNetwork: "Disabled"
    apiVIP: <API_VIP>
    ingressVIP: <INGRESS_VIP>
    hosts:
      - name: master-0
        role: master
        bmc:
          address: idrac-virtualmedia://<BMC_IP_MASTER_0>/redfish/v1/Systems/System.Embedded.1
          username: <BMC_USERNAME>
          password: <BMC_PASSWORD>
          disableCertificateVerification: True
        bootMACAddress: <BOOT_MAC_MASTER_0>
        rootDeviceHints:
          deviceName: "/dev/sda"
        networkConfig:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                address:
                - ip: <IP_MASTER_0>
                  prefix-length: <NETWORK_PREFIX_LENGTH>
                enabled: true
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
              mac-address: <BOOT_MAC_MASTER_0>
            - name: eno2
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
                address:
            - name: ens2f0
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
            - name: ens2f1
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
          dns-resolver:
            config:
              server:
              - <DNS_SERVER>
          routes:
            config:
              - destination: '0.0.0.0/0'
                next-hop-address: <GATEWAY>
                next-hop-interface: eno1
                metric: 40
      - name: master-1
        role: master
        bmc:
          address: idrac-virtualmedia://<BMC_IP_MASTER_1>/redfish/v1/Systems/System.Embedded.1
          username: <BMC_USERNAME>
          password: <BMC_PASSWORD>
          disableCertificateVerification: True
        bootMACAddress: <BOOT_MAC_MASTER_1>
        rootDeviceHints:
          deviceName: "/dev/sda"
        networkConfig:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                address:
                - ip: <IP_MASTER_1>
                  prefix-length: <NETWORK_PREFIX_LENGTH>
                enabled: true
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
              mac-address: <BOOT_MAC_MASTER_1>
            - name: eno2
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
                address:
            - name: ens2f0
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
            - name: ens2f1
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
          dns-resolver:
            config:
              server:
              - <DNS_SERVER>
          routes:
            config:
              - destination: '0.0.0.0/0'
                next-hop-address: <GATEWAY>
                next-hop-interface: eno1
                metric: 40
      - name: master-2
        role: master
        bmc:
          address: idrac-virtualmedia://<BMC_IP_MASTER_2>/redfish/v1/Systems/System.Embedded.1
          username: <BMC_USERNAME>
          password: <BMC_PASSWORD>
          disableCertificateVerification: True
        bootMACAddress: <BOOT_MAC_MASTER_2>
        rootDeviceHints:
          deviceName: "/dev/sda"
        networkConfig:
          interfaces:
            - name: eno1
              type: ethernet
              state: up
              ipv4:
                address:
                - ip: <IP_MASTER_2>
                  prefix-length: <NETWORK_PREFIX_LENGTH>
                enabled: true
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
              mac-address: <BOOT_MAC_MASTER_2>
            - name: eno2
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
            - name: ens3f0
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
            - name: ens3f1
              type: ethernet
              state: absent
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                enabled: false
                dhcp: false
          dns-resolver:
            config:
              server:
              - <DNS_SERVER>
          routes:
            config:
              - destination: '0.0.0.0/0'
                next-hop-address: <GATEWAY>
                next-hop-interface: eno1
                metric: 40
pullSecret: '<PULL_SECRET>'
sshKey: '<SSH_PUBLIC_KEY>'
