apiVersion: v1
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
data:
  AdminPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  AodhPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  AodhDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  BarbicanDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  BarbicanPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  BarbicanSimpleCryptoKEK: TU1vNzlyS01nNFRpdWtBYWZPcVZ5VlcwQ0xzMGlQcDI2dXhZRVZfZ1U3WT0K
  CeilometerPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  CinderDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  CinderPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  DatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  DbRootPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  DesignateDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  DesignatePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  GlanceDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  GlancePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  HeatAuthEncryptionKey: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  HeatDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  HeatPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  IronicDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  IronicInspectorDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  IronicInspectorPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  IronicPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  KeystoneDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  ManilaDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  ManilaPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  MetadataSecret: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NeutronDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NeutronPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaAPIDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaAPIMessageBusPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaCell0DatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaCell0MessageBusPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaCell1DatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaCell1MessageBusPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  NovaPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  OctaviaDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  OctaviaPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  PlacementDatabasePassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  PlacementPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
  SwiftPassword: QjJESlRDQlVoNjdKRjZMOTFqZDBKdlFWMDhnZXZ0eUI=
