apiVersion: v1
kind: Secret
metadata:
  name: osp-secret
  namespace: openstack
type: Opaque
data:
  AdminPassword: Z0eUI=
  AodhPassword: Z0eUI=
  AodhDatabasePassword: Z0eUI=
  BarbicanDatabasePassword: Z0eUI=
  BarbicanPassword: Z0eUI=
  BarbicanSimpleCryptoKEK: 1U3WT0K
  CeilometerPassword: Z0eUI=
  CinderDatabasePassword: Z0eUI=
  CinderPassword: Z0eUI=
  DatabasePassword: Z0eUI=
  DbRootPassword: Z0eUI=
  DesignateDatabasePassword: Z0eUI=
  DesignatePassword: Z0eUI=
  GlanceDatabasePassword: Z0eUI=
  GlancePassword: Z0eUI=
  HeatAuthEncryptionKey: Z0eUI=
  HeatDatabasePassword: Z0eUI=
  HeatPassword: Z0eUI=
  IronicDatabasePassword: Z0eUI=
  IronicInspectorDatabasePassword: Z0eUI=
  IronicInspectorPassword: Z0eUI=
  IronicPassword: Z0eUI=
  KeystoneDatabasePassword: Z0eUI=
  ManilaDatabasePassword: Z0eUI=
  ManilaPassword: Z0eUI=
  MetadataSecret: Z0eUI=
  NeutronDatabasePassword: Z0eUI=
  NeutronPassword: Z0eUI=
  NovaAPIDatabasePassword: Z0eUI=
  NovaAPIMessageBusPassword: Z0eUI=
  NovaCell0DatabasePassword: Z0eUI=
  NovaCell0MessageBusPassword: Z0eUI=
  NovaCell1DatabasePassword: Z0eUI=
  NovaCell1MessageBusPassword: Z0eUI=
  NovaPassword: Z0eUI=
  OctaviaDatabasePassword: Z0eUI=
  OctaviaPassword: Z0eUI=
  PlacementDatabasePassword: Z0eUI=
  PlacementPassword: Z0eUI=
  SwiftPassword: Z0eUI=
