apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: osp-enp7s0f1np1-host-192-168-60-178
spec:
  desiredState:
    interfaces:
      - description: internalapi vlan interface
        ipv4:
          address:
            - ip: 172.17.0.15
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: internalapi
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "393"
          reorder-headers: true

      - description: tenant vlan interface
        ipv4:
          address:
            - ip: 172.19.0.16
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        name: tenant
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "429"
          reorder-headers: true
      
      - description: OBM vlan interface for moc-obm-mgmt
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
        mtu: 1500
        name: obm
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "911"
          reorder-headers: true

      - description: Dev vlan interface for moc-dev-net
        ipv4:
          enabled: true
          dhcp: true
        ipv6:
          enabled: false
        mtu: 1500
        name: devnet
        state: up
        type: vlan
        vlan:
          base-iface: enp7s0f1np1
          id: "914"
          reorder-headers: true

      - description: Physical trunk interface for VLANs and bridge
        name: enp7s0f1np1
        type: ethernet
        state: up
        mtu: 1500
        ipv4:
          enabled: false
        ipv6:
          enabled: false

      - description: ospbr bridge over enp7s0f1np1 with ctlplane IP
        name: ospbr
        type: linux-bridge
        state: up
        mtu: 1500
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp7s0f1np1
              vlan: {}
        ipv4:
          address:
            - ip: 192.168.122.18
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
          
      - description: ironic vlan interface
        ipv4:
          address:
            - ip: 172.20.1.17
              prefix-length: "24"
          enabled: true
          dhcp: false
        ipv6:
          enabled: false
        mtu: 1500
        name: ironic
        state: up
        type: vlan
        vlan:
          base-iface: ospbr
          id: "596"
          reorder-headers: true

  nodeSelector:
    kubernetes.io/hostname: host-192-168-60-178
    node-role.kubernetes.io/worker: ""
